# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mooclet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoocletVersionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_function', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.IntegerField(blank=True, null=True)),
                ('var2', models.IntegerField(blank=True, null=True)),
                ('var3', models.IntegerField(blank=True, null=True)),
                ('var4', models.IntegerField(blank=True, null=True)),
                ('var5', models.IntegerField(blank=True, null=True)),
                ('var6', models.IntegerField(blank=True, null=True)),
                ('var7', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroupProbabilityArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Mooclet')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.SubGroup')),
            ],
        ),
        migrations.CreateModel(
            name='UserVarMoocletVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Mooclet')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Policy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Student')),
            ],
        ),
        migrations.CreateModel(
            name='UserVarNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=250, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Student')),
            ],
        ),
        migrations.CreateModel(
            name='UserVarText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(blank=True, max_length=2000, null=True)),
                ('descriptor', models.CharField(max_length=250)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Mooclet')),
            ],
        ),
        migrations.CreateModel(
            name='VersionProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('subgroup_probability_array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.SubGroupProbabilityArray')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Version')),
            ],
        ),
        migrations.AddField(
            model_name='uservarmoocletversion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Version'),
        ),
        migrations.AddField(
            model_name='moocletversionvalue',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Version'),
        ),
    ]
