# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mooclet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.IntegerField()),
                ('var2', models.IntegerField()),
                ('var3', models.IntegerField()),
                ('var4', models.IntegerField()),
                ('var5', models.IntegerField()),
                ('var6', models.IntegerField()),
                ('var7', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubGroupProbabilityArray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Mooclet')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.SubGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Mooclet')),
            ],
        ),
        migrations.CreateModel(
            name='VersionProbability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField()),
                ('subgroup_probability_array', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.SubGroupProbabilityArray')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Version')),
            ],
        ),
    ]
