# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moocletpolicy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='var1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='var2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='var3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='var4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='var5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='var6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='var7',
            field=models.IntegerField(null=True),
        ),
    ]
