# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moocletpolicy', '0004_auto_20160607_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_function', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserVarMoocletVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mooclet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Mooclet')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Policy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Student')),
            ],
        ),
        migrations.CreateModel(
            name='UserVarNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.FloatField(blank=True, null=True)),
                ('descriptor', models.CharField(blank=True, max_length=250, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Student')),
            ],
        ),
        migrations.CreateModel(
            name='UserVarText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('var_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('descriptor', models.CharField(max_length=250)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Student')),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='uservarmoocletversion',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moocletpolicy.Version'),
        ),
    ]
