# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moocletpolicy', '0005_auto_20160617_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uservartext',
            old_name='var_value',
            new_name='value',
        ),
    ]
