# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moocletpolicy', '0006_auto_20160617_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_function',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
